### evalSampPt ###
# This function will evaluate the enveloping and sandwiching functions
# at the point generated by sampleUp. The returned values are meant
# to be used to see whether to reject the sample point or not.
## Input: 'x' is the potential sample point
##        'UpHull' is the dataframe for the upper boundary
##        'LowHull' is the dataframe for the lower boundary
## Output: 'lEval' is the value of the sandwiching function at the sample point
##         'uEval' is the value of the enveloping function at the sample point

evalSampPt = function(x, UpHull, LowHull) {
  
  
  # Evaluate lower bound at sample point
  if (x < min(LowHull$left)) {
    lEval = -Inf
  } else if (x > max(LowHull$right)) {
    lEval = -Inf
  } else {
    # Determine which set of information to use
    ind = which(x >= LowHull$left & x <= LowHull$right, arr.ind = TRUE) 
    lEval = LowHull$m[ind] * x + LowHull$b[ind]
  }
  
  # Evaluate upper bound at sample point
  indR = which(x >= UpHull$left & x <= UpHull$right, arr.ind = TRUE)
  uEval = UpHull$m[indR] * x + UpHull$b[indR]
  
  return(c(lEval, uEval))
}