#' @include sampleFromUp.R
#' @include UpperandLower.R
#' @include StartingPoints.R
#' @include Rejection_Test.R
#' 
#' @name evalSampPt
#' 
#' @title Evaluate the enveloping and sandwiching functions
#' 
#' @description
#' This function will evaluate the enveloping and sandwiching functions
#' at the point generated by sampleUp. The returned values are meant
#' to be used to see whether to reject the sample point or not.
#'
#' @param x potential sample point
#' @param UpHull dataframe for the upper boundary
#' @param LowHull dataframe for the lower boundary
#' @return lEval value of the sandwiching function at the sample point
#' @return uEval value of the enveloping function at the sample point

evalSampPt = function(x, UpHull, LowHull) {
  
  
  # Evaluate lower bound at sample point
  if (x < min(LowHull$left)) {
    lEval = -Inf
  } else if (x > max(LowHull$right)) {
    lEval = -Inf
  } else {
    # Determine which set of information to use
    ind = which(x >= LowHull$left & x <= LowHull$right, arr.ind = TRUE) 
    lEval = LowHull$m[ind] * x + LowHull$b[ind]
  }
  
  # Evaluate upper bound at sample point
  indR = which(x >= UpHull$left & x <= UpHull$right, arr.ind = TRUE)
  uEval = UpHull$m[indR] * x + UpHull$b[indR]
  
  return(c(lEval, uEval))
}