#' @include evalSampPt.R
#' @include UpperandLower.R
#' @include StartingPoints.R
#' @include Rejection_Test.R
#' 
#' @name sampleUp 
#' 
#' @title This function will generate a potential sample point from
#' the enveloping function.
#' 
#' @param UpperHull the dataframe generated by createUpHull
#' 
#' @return x a single point

sampleUp = function(UpperHull) {
  
  emp.cdf = cumsum(UpperHull$prob)
  IsInf = TRUE # repeat until sample is valid
  while(IsInf) {
    u = runif(1)
    ind = min(which(u<emp.cdf, arr.ind = TRUE))
    u = runif(1)
    m = UpperHull$m[ind]
    b = UpperHull$b[ind]
    left = UpperHull$left[ind]
    right = UpperHull$right[ind]
  
    x = log( u*(exp(m*right) - exp(m*left)) + exp(m*left) ) / m
    if (!is.infinite(x) & !is.nan(x) & !is.na(x)) {
      IsInf = FALSE
    }
  
  
  }
  
  return(x)
}